# This file was auto generated Wed Feb 18 15:58:37 2009 by create_db_files.pl
# DO NOT EDIT BUT RERUN THE SCRIPT!
package Varnish::DB_Data;

my %parameter_field = (
'accept_fd_holdoff' => {value => '50'},
'auto_restart' => {value => 'on'},
'backend_http11' => {value => 'on'},
'between_bytes_timeout' => {value => '60.000000'},
'cache_vbe_conns' => {value => 'off'},
'cc_command' => {value => '"exec cc -fpic -shared -Wl,-x -o %o %s"'},
'cli_banner' => {value => 'on'},
'cli_buffer' => {value => '8192'},
'cli_timeout' => {value => '5'},
'client_http11' => {value => 'off'},
'clock_skew' => {value => '10'},
'connect_timeout' => {value => '0.400000'},
'default_grace' => {value => '10'},
'default_ttl' => {value => '120'},
'diag_bitmap' => {value => '0x0'},
'err_ttl' => {value => '0'},
'esi_syntax' => {value => '0'},
'fetch_chunksize' => {value => '128'},
'first_byte_timeout' => {value => '60.000000'},
'group' => {value => 'nogroup'},
'listen_address' => {value => ':80'},
'listen_depth' => {value => '1024'},
'log_hashstring' => {value => 'off'},
'log_local_address' => {value => 'off'},
'lru_interval' => {value => '2'},
'max_esi_includes' => {value => '5'},
'max_restarts' => {value => '4'},
'obj_workspace' => {value => '8192'},
'overflow_max' => {value => '100'},
'ping_interval' => {value => '3'},
'pipe_timeout' => {value => '60'},
'prefer_ipv6' => {value => 'off'},
'purge_dups' => {value => 'off'},
'purge_hash' => {value => 'off'},
'rush_exponent' => {value => '3'},
'send_timeout' => {value => '600'},
'sess_timeout' => {value => '5'},
'sess_workspace' => {value => '16384'},
'session_linger' => {value => '0'},
'shm_reclen' => {value => '255'},
'shm_workspace' => {value => '8192'},
'srcaddr_hash' => {value => '1049'},
'srcaddr_ttl' => {value => '30'},
'thread_pool_add_delay' => {value => '20'},
'thread_pool_add_threshold' => {value => '2'},
'thread_pool_fail_delay' => {value => '200'},
'thread_pool_max' => {value => '500'},
'thread_pool_min' => {value => '5'},
'thread_pool_purge_delay' => {value => '1000'},
'thread_pool_timeout' => {value => '300'},
'thread_pools' => {value => '2'},
'user' => {value => 'nobody'},
'vcl_trace' => {value => 'off'},
'waiter' => {value => 'default'},
);
my %stat_field_exist = ('session_pipeline' => 1,
'shm_mtx_contention' => 1,
'n_overflowed_work_requests' => 1,
'backend_connections_failures' => 1,
'n_worker_threads_limited' => 1,
'sma_outstanding_bytes' => 1,
'backend_connections_too_many' => 1,
'shm_cycles_through_buffer' => 1,
'esi_parse_errors__unlock_' => 1,
'total_pipe' => 1,
'n_worker_threads_created' => 1,
'objects_sent_with_write' => 1,
'backend_connections_success' => 1,
'n_dropped_work_requests' => 1,
'objects_overflowing_workspace' => 1,
'sms_outstanding_bytes' => 1,
'client_requests_received' => 1,
'n_objects_on_deathrow' => 1,
'n_total_active_purges' => 1,
'backend_requests_made' => 1,
'bytes_allocated' => 1,
'outstanding_allocations' => 1,
'objects_esi_parsed__unlock_' => 1,
'n_struct_vbe_conn' => 1,
'cache_hits_for_pass' => 1,
'n_lru_saved_objects' => 1,
'cache_hits' => 1,
'sma_outstanding_allocations' => 1,
'total_pass' => 1,
'backend_connections_reuses' => 1,
'backend_connections_not_attempted' => 1,
'shm_flushes_due_to_overflow' => 1,
'n_duplicate_purges_removed' => 1,
'n_new_purges_added' => 1,
'session_closed' => 1,
'cache_misses' => 1,
'n_struct_srcaddr' => 1,
'sms_allocator_requests' => 1,
'session_herd' => 1,
'n_worker_threads_not_created' => 1,
'n_vcl_discarded' => 1,
'hcb_lookups_without_lock' => 1,
'n_worker_threads' => 1,
'n_lru_nuked_objects' => 1,
'n_queued_work_requests' => 1,
'total_sessions' => 1,
'total_header_bytes' => 1,
'n_objects_tested' => 1,
'n_active_struct_srcaddr' => 1,
'bytes_free' => 1,
'n_vcl_total' => 1,
'n_backends' => 1,
'sma_bytes_free' => 1,
'total_body_bytes' => 1,
'shm_records' => 1,
'n_vcl_available' => 1,
'sma_bytes_allocated' => 1,
'objects_sent_with_sendfile' => 1,
'hcb_lookups_with_lock' => 1,
'n_struct_sess_mem' => 1,
'client_connections_accepted' => 1,
'n_struct_bereq' => 1,
'sms_bytes_freed' => 1,
'sms_outstanding_allocations' => 1,
'sms_bytes_allocated' => 1,
'n_small_free_smf' => 1,
'n_struct_objecthead' => 1,
'total_fetch' => 1,
'sma_allocator_requests' => 1,
'backend_connections_recycles' => 1,
'backend_connections_unused' => 1,
'shm_writes' => 1,
'n_struct_object' => 1,
'total_requests' => 1,
'hcb_inserts' => 1,
'n_lru_moved_objects' => 1,
'n_struct_sess' => 1,
'allocator_requests' => 1,
'n_regexps_tested_against' => 1,
'n_expired_objects' => 1,
'http_header_overflows' => 1,
'n_struct_smf' => 1,
'n_old_purges_deleted' => 1,
'n_large_free_smf' => 1,
'session_read_ahead' => 1,
'session_linger' => 1,
);
sub get_parameter_field() { return \%parameter_field; }sub get_stat_field_exist() { return \%stat_field_exist; }
1;
